---
- name: Reading csv file
  read_csv:
   path: users.csv
  register: user_list
  delegate_to: localhost

- name: Create new users
  user:
   name: "{{ item.Username }}"
   group: "{{ conda_user_group }}"
   password: "{{ item.Password | password_hash('sha512') }}"
   create_home: yes
  #  state: absent
  #  remove: yes
  #  force: yes
   shell: "/bin/bash"
  loop: "{{ user_list.list }}"
  when: ansible_ssh_host == item.Host
  become: yes

- name: Set permission for user env folder
  ansible.builtin.file:
    path: "/home/{{ item.Username }}/.conda/envs"
    owner: "{{ item.Username }}"
    group: "{{ conda_user_group }}"
    state: directory
    recurse: yes
    force: yes
  loop: "{{ user_list.list }}"
  when: ansible_ssh_host == item.Host
  become: yes

- name: Populate conda env for each user
  shell: '"{{ miniconda_prefix }}/bin/mamba" create -p /home/{{ item.Username }}/.conda/envs/{{ item.Username }} seqkit -y -q && chown -R {{  item.Username }}: /home/{{ item.Username }}/.conda'
  loop: "{{ user_list.list }}"
  when: ansible_ssh_host == item.Host
  become: yes

- name: Copy bashrc with predefined conda env
  ansible.builtin.template:
    src: "./files/bashrc.j2"
    dest: "/home/{{ item.Username }}/.bashrc"
    owner: "{{ item.Username }}"
    mode: u=rw,g=r,o=r
  loop: "{{ user_list.list }}"
  when: ansible_ssh_host == item.Host
  become: yes
